# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'weletranslations'
tagline:             'Translating since 1917'
description:         'A blog focused on the translation of Xianxia novels'
url:                 http://neogranular.github.io
baseurl:             'http://neogranular.github.io'
paginate:            5

# About/contact
author:
  name:              NG
  url:               http://weletranslation.com/
  email:             none@localhost

# Website layout designed by Mark Otto

# Custom vars
version:             1.0.0
