# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
#relative_permalinks: true

# Setup
title:               'weletranslations'
tagline:             'Translating since 1917'
description:         'A blog focused on the translation of Xianxia novels'
url:                 http://weletranslation.com
baseurl:             'http://weletranslation.com'
paginate:            5
timezone:            'Europe/Berlin'

# About/contact
author:
  name:              weletranslations
  url:               http://weletranslation.com/
  email:             nakedgod380@gmail.com

# Website layout designed by Mark Otto

# Custom vars
version:             1.0.0
excerpt_separator: <!--more-->

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: all

gems: [jekyll-paginate]
